# -*- coding: utf-8 -*-
import os
import sys
import re
import shutil
import argparse

# Setup working directory within the skill root
SKILL_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORKING_DIR = os.path.join(SKILL_ROOT, "working")
WORKSPACE_ROOT = os.getcwd()

def ensure_working_dir():
    if not os.path.exists(WORKING_DIR):
        os.makedirs(WORKING_DIR)

def get_next_session_num():
    ensure_working_dir()
    num = 1
    while True:
        md_file = os.path.join(WORKING_DIR, "qna{}.md".format(num))
        if not os.path.exists(md_file):
            return num
        num += 1

def init_session():
    num = get_next_session_num()
    md_file = os.path.join(WORKING_DIR, "qna{}.md".format(num))
    with open(md_file, "w", encoding="utf-8") as f:
        f.write("")
    print("SESSION_INITIALIZED:{}".format(num))
    return num

def append_qna(num, question, answer):
    ensure_working_dir()
    md_file = os.path.join(WORKING_DIR, "qna{}.md".format(num))
    
    q_num = 1
    if os.path.exists(md_file):
        with open(md_file, "r", encoding="utf-8") as f:
            content = f.read()
        matches = re.findall(r"^##\s+Q(\d+)", content, re.MULTILINE)
        if matches:
            q_num = max(int(m) for m in matches) + 1

    qa_block = "## Q{}\n{}\n\n### A\n{}\n\n".format(q_num, question.strip(), answer.strip())
    
    with open(md_file, "a", encoding="utf-8") as f:
        f.write(qa_block)
    print("QNA_APPENDED:{} to qna{}.md".format(q_num, num))

def markdown_to_html_body(md_content):
    import markdown
    
    # Process github-style alerts first
    def alert_repl(match):
        alert_type = match.group(1).upper()
        raw_lines = match.group(2).split('\n')
        content_lines = []
        for l in raw_lines:
            l_strip = l.strip()
            if l_strip.startswith('>'):
                content_lines.append(l_strip[1:].strip())
            else:
                content_lines.append(l_strip)
        content_text = "\n".join(content_lines).strip()
        
        # Parse inner alert contents with markdown
        inner_html = markdown.markdown(content_text, extensions=['fenced_code', 'tables'])
        return '\n\n<div class="alert alert-{}"><strong>[{}]</strong> {}</div>\n\n'.format(alert_type.lower(), alert_type, inner_html)
        
    pattern = r"^>\s+\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\n((?:>\s+.*?(?:\n|$))*)"
    processed = re.sub(pattern, alert_repl, md_content, flags=re.MULTILINE)
    
    # Single-line alerts fallback
    pattern_single = r"^>\s+\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\n>\s+(.*?)$"
    processed = re.sub(pattern_single, lambda m: '<div class="alert alert-{}"><strong>[{}]</strong> {}</div>'.format(m.group(1).lower(), m.group(1), markdown.markdown(m.group(2).strip())), processed, flags=re.MULTILINE)

    # Pre-process: Auto-align improperly indented fenced code blocks (commonly generated by AI in lists)
    # This strips leading spaces so the parser recognizes them strictly as blocks, not continuation text.
    processed = re.sub(r"^\s+```([a-zA-Z0-9-]*)$", r"```\1", processed, flags=re.MULTILINE)

    html = markdown.markdown(processed, extensions=['fenced_code', 'tables'])
    return html

def parse_md_to_qa_list(md_file):
    if not os.path.exists(md_file):
        return []
    with open(md_file, "r", encoding="utf-8") as f:
        content = f.read()
    
    sections = re.split(r"\n##\s+Q\d+", "\n" + content)
    headers = re.findall(r"\n##\s+Q(\d+)", "\n" + content)
    
    qa_pairs = []
    for idx, sec in enumerate(sections[1:]):
        q_num = headers[idx] if idx < len(headers) else str(idx + 1)
        parts = sec.split("### A", 1)
        raw_question = parts[0].strip()
        answer_md = parts[1].strip() if len(parts) > 1 else ""
        
        # Segment the question paragraph dynamically to separate primary questions from intro chat logs
        q_paragraphs = raw_question.split('\n\n')
        question_md = q_paragraphs[0].strip()
        
        if len(q_paragraphs) > 1:
            rest_of_q = "\n\n".join(q_paragraphs[1:]).strip()
            answer_md = rest_of_q + "\n\n" + answer_md
            answer_md = answer_md.strip()
            
        qa_pairs.append({
            "num": q_num,
            "question_md": question_md,
            "answer_md": answer_md,
            "question_html": markdown_to_html_body(question_md),
            "answer_html": markdown_to_html_body(answer_md)
        })
    return qa_pairs

def cleanse_overall_text(text):
    if not text:
        return ""
        
    # 1. Multi-line pattern matching to clean conversational paragraphs
    text = re.sub(
        r"Gemini\s+Flash\s+웹\s*[채체]킹에\s+문의해본\s+결과.*?(?:---|정리해\s+드릴게요\.?)\s*\n",
        "",
        text,
        flags=re.DOTALL | re.IGNORECASE
    )
    
    # Clean any remaining empty markdown code wrappers
    text = re.sub(r"```markdown\s*```", "", text)
    text = re.sub(r"```\s*```", "", text)
    
    lines = text.split('\n')
    cleaned_lines = []
    
    # List of conversational/chat transition filters in Korean
    fillers = [
        r"네,\s+\*\*충분히\s+가능합니다\*\*",
        r"네,\s+충분히\s+가능합니다",
        r"이를\s+구현하기\s+위해.*정리해\s+드릴게요",
        r"이를\s+구현하기\s+위해.*정리해\s+드립니다",
        r"아래와\s+같이.*정리해\s+드립니다",
        r"핵심\s+요약은\s+다음과\s+같습니다",
        r"자세한\s+내용은.*참고해\s+주시기\s+바랍니다",
        r"질문\s+답변\s+내용을\s+보고",
        r"다음의\s+응답을\s+얻었는데",
        r"문의해본\s+결과",
        r"참고해\s+주시기\s+바랍니다"
    ]
    
    for line in lines:
        stripped = line.strip()
        is_filler = False
        
        # Check if line matches conversational rules
        for pattern in fillers:
            if re.search(pattern, stripped, re.IGNORECASE):
                is_filler = True
                break
                
        # Also drop line if it is just a conversational wrap-up
        if stripped.endswith("정리해 드립니다.") or stripped.endswith("정리해 드릴게요.") or stripped.endswith("정리해 드릴게요"):
            is_filler = True
            
        if not is_filler:
            cleaned_lines.append(line)
            
    result = "\n".join(cleaned_lines).strip()
    result = re.sub(r"^---\s*$", "", result, flags=re.MULTILINE)
    return result.strip()

def assign_block_to_topic(raw_header_line, content, topics, q_num):
    content = cleanse_overall_text(content)
    
    # Determine the heading depth from the number of '#' characters
    depth_match = re.match(r"^(#+)", raw_header_line.strip())
    header_depth = len(depth_match.group(1)) if depth_match else 4
    
    header_clean = raw_header_line.strip().replace('#', '').strip()
    
    # Cleanse leading numeric or serial prefixes (e.g. "3. 🛠️ 최종 점검..." -> "🛠️ 최종 점검...")
    header_clean = re.sub(r"^\d+[\.\)]\s*", "", header_clean)
    header_clean = re.sub(r"^[①-⑩]\s*", "", header_clean)
    header_clean = header_clean.strip()
    
    content_lines = content.strip().split('\n')
    
    if content_lines:
        first_line_clean = content_lines[0].strip().replace('#', '').strip()
        first_line_clean = re.sub(r"^\d+[\.\)]\s*", "", first_line_clean)
        first_line_clean = re.sub(r"^[①-⑩]\s*", "", first_line_clean).strip()
        
        if first_line_clean == header_clean or first_line_clean.startswith(header_clean) or header_clean.startswith(first_line_clean):
            content = "\n".join(content_lines[1:]).strip()
            
    content = cleanse_overall_text(content)
            
    # Do not skip if content is empty but acts as a structural parent holding child headings
    if not content.strip():
        return
    if len(content.strip()) < 10 and not any(l.strip().startswith('#') for l in content.split('\n')):
        return
        
    combined_text = (header_clean + "\n" + content).lower()
    
    best_topic = "uncategorized"
    best_score = 0
    
    for key, topic_info in topics.items():
        if key == "uncategorized":
            continue
        score = 0
        for kw in topic_info["keywords"]:
            if kw in combined_text:
                score += 2
        
        # Override to direct file picker features to the "features" category (Topic 2)
        if key == "features" and any(w in combined_text for w in ["파일 열기", "파일 저장", "picker", "editor", "텍스트 수정", "저장", "탐색", "finder"]):
            score += 15
            
        # Override to direct monetization elements to the "monetization" category (Topic 3)
        if key == "monetization" and any(w in combined_text for w in ["admob", "adsense", "수익", "수익화", "광고", "결제", "애드센스", "애드몹"]):
            score += 15
            
        # Override to direct setup configurations to "environment" (Topic 4)
        if key == "environment" and any(w in combined_text for w in ["설치", "sdk", "환경 설정", "빌드", "ide"]):
            score += 15
        
        # Apply standard weight coefficients from Q-number origins
        if q_num == "1" and key in ["framework", "features"]:
            score += 3
        elif q_num == "2" and key == "monetization":
            score += 5
        elif q_num == "3" and key == "environment":
            score += 5
            
        if score > best_score:
            best_score = score
            best_topic = key
            
    if best_score == 0:
        if q_num == "1":
            best_topic = "framework"
        elif q_num == "2":
            best_topic = "monetization"
        elif q_num == "3":
            best_topic = "environment"
        else:
            best_topic = "uncategorized"
            
    cleaned_header = header_clean
    cleaned_header = re.sub(r"\bQ\d+\b\s*(관련)?\s*(세부\s*사항|세부 사항|내용|기록)?", "", cleaned_header, flags=re.IGNORECASE)
    cleaned_header = cleaned_header.strip()
    
    if not cleaned_header or cleaned_header.lower() in ["기본 가이드라인", "기본 가이드", "기본사항", "개요 및 아키텍처 가이드"]:
        if best_topic == "framework":
            cleaned_header = "아키텍처 개요"
        elif best_topic == "features":
            cleaned_header = "핵심 구현 스펙"
        elif best_topic == "monetization":
            cleaned_header = "수익화 모델 개요"
        elif best_topic == "environment":
            cleaned_header = "플랫폼 가이드라인"
        else:
            cleaned_header = "요약 개요"
            
    topics[best_topic]["blocks"].append({
        "header": cleaned_header,
        "content_md": content,
        "content_html": markdown_to_html_body(content),
        "depth": header_depth
    })

def compile_overall_by_topics(qa_list):
    topics = {
        "framework": {
            "title": "🛠️ 개발 프레임워크 및 아키텍처",
            "keywords": ["프레임워크", "flutter", "react", "native", "플랫폼", "cross", "크로스"],
            "blocks": []
        },
        "features": {
            "title": "📂 앱 핵심 기능 및 파일 제어 스펙",
            "keywords": ["파일", "탐색", "finder", "picker", "editor", "텍스트 수정", "구현 흐름", "기능"],
            "blocks": []
        },
        "monetization": {
            "title": "💰 광고 수익 모델 및 플랫폼 규정",
            "keywords": ["광고", "수익", "admob", "adsense", "결제", "수수료", "정책", "제한", "우회"],
            "blocks": []
        },
        "environment": {
            "title": "⚙️ 플랫폼별 개발 환경 가이드",
            "keywords": ["환경", "설정", "sdk", "빌드", "타겟", "macos", "windows", "ios", "android"],
            "blocks": []
        },
        "uncategorized": {
            "title": "📋 기타 세션 상세 내역",
            "keywords": [],
            "blocks": []
        }
    }
    
    for qa in qa_list:
        answer_md = qa["answer_md"]
        lines = answer_md.split('\n')
        current_block_header = "#### 기본 가이드라인"
        current_block_lines = []
        
        for line in lines:
            line_str = line.strip()
            # Match any headings H3, H4, H5
            if line_str.startswith('#####') or line_str.startswith('####') or line_str.startswith('###'):
                if current_block_lines:
                    block_content = "\n".join(current_block_lines).strip()
                    assign_block_to_topic(current_block_header, block_content, topics, qa["num"])
                current_block_header = line.strip()
                current_block_lines = [line]
            else:
                current_block_lines.append(line)
                
        if current_block_lines:
            block_content = "\n".join(current_block_lines).strip()
            assign_block_to_topic(current_block_header, block_content, topics, qa["num"])
            
    return topics

def get_unique_filepath(filepath):
    if not os.path.exists(filepath):
        return filepath
    dir_name = os.path.dirname(filepath)
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    num = 1
    while True:
        new_name = "{}-{}{}".format(name, num, ext)
        new_path = os.path.join(dir_name, new_name)
        if not os.path.exists(new_path):
            return new_path
        num += 1

def resolve_output_path(output_arg, default_filename):
    if not output_arg:
        return get_unique_filepath(os.path.join(WORKSPACE_ROOT, default_filename))
    
    full_path = output_arg
    if not os.path.isabs(full_path):
        full_path = os.path.join(WORKSPACE_ROOT, full_path)
        
    if os.path.isdir(full_path):
        full_path = os.path.join(full_path, default_filename)
        
    parent_dir = os.path.dirname(full_path)
    if parent_dir and not os.path.exists(parent_dir):
        os.makedirs(parent_dir)
        
    return get_unique_filepath(full_path)

def generate_html_string(title, left_toc, content_cards, right_toc, is_overall):
    subtitle = "주제별 종합 기술 스펙서" if is_overall else "Q&A 세션 상세 기록"
    brand_sub = "Overall" if is_overall else "Detail"
    
    template = """<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{TITLE}</title>
    <link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism-tomorrow.min.css" rel="stylesheet" />
    <style>
        :root {
            --bg-dark: #0b0f19;
            --bg-sidebar: #0f1422;
            --bg-card: #151b2d;
            --bg-hover: rgba(255, 255, 255, 0.03);
            --border: rgba(255, 255, 255, 0.08);
            --border-active: #06b6d4;
            --text-primary: #f3f4f6;
            --text-secondary: #a1a8b9;
            --text-muted: #6b7280;
            --accent-cyan: #06b6d4;
            --accent-teal: #0d9488;
            --accent-gradient: linear-gradient(135deg, #06b6d4 0%, #0d9488 100%);
            --font-body: 'Pretendard', -apple-system, BlinkMacSystemFont, system-ui, Roboto, sans-serif;
            --font-title: 'Pretendard', -apple-system, BlinkMacSystemFont, system-ui, Roboto, sans-serif;
            --font-mono: 'JetBrains Mono', monospace;
        }
        
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            background-color: var(--bg-dark);
            color: var(--text-primary);
            font-family: var(--font-body);
            display: grid;
            grid-template-columns: 280px 1fr 280px;
            min-height: 100vh;
            line-height: 1.75;
        }
        
        /* Left Sidebar: Topic Categorization */
        .left-sidebar {
            background-color: var(--bg-sidebar);
            border-right: 1px solid var(--border);
            padding: 30px 20px;
            display: flex;
            flex-direction: column;
            gap: 30px;
            position: sticky;
            top: 0;
            height: 100vh;
            overflow-y: auto;
            z-index: 100;
        }
        
        /* Right Sidebar: Document TOC */
        .right-sidebar {
            background-color: var(--bg-sidebar);
            border-left: 1px solid var(--border);
            padding: 30px 20px;
            display: flex;
            flex-direction: column;
            gap: 20px;
            position: sticky;
            top: 0;
            height: 100vh;
            overflow-y: auto;
            z-index: 100;
        }
        
        .brand {
            display: flex;
            align-items: center;
            gap: 12px;
        }
        .brand-logo {
            width: 32px;
            height: 32px;
            background: var(--accent-gradient);
            border-radius: 8px;
        }
        .brand-title {
            font-family: var(--font-title);
            font-weight: 800;
            font-size: 1.25rem;
            letter-spacing: -0.02em;
        }
        .brand-title span {
            color: var(--accent-cyan);
        }
        
        /* Navigation Links (Left) */
        .nav-list {
            list-style: none;
            display: flex;
            flex-direction: column;
            gap: 12px;
        }
        .nav-list li a {
            display: block;
            color: var(--text-secondary);
            text-decoration: none;
            font-size: 0.85rem;
            font-weight: 500;
            padding: 10px 12px;
            border-radius: 8px;
            transition: all 0.2s;
            border: 1px solid transparent;
            text-overflow: ellipsis;
            white-space: nowrap;
            overflow: hidden;
        }
        .nav-list li a:hover, .nav-list li a.active {
            background-color: rgba(255, 255, 255, 0.02);
            color: var(--text-primary);
            border-color: var(--border);
            box-shadow: 0 4px 12px rgba(6, 182, 212, 0.05);
        }
        .nav-list li a.active {
            border-color: var(--border-active);
            color: var(--accent-cyan);
        }
        
        .num-badge {
            font-family: var(--font-title);
            font-weight: 800;
            background-color: rgba(6, 182, 212, 0.1);
            color: var(--accent-cyan);
            padding: 2px 8px;
            border-radius: 6px;
            font-size: 0.75rem;
            margin-right: 6px;
        }
        
        /* Table of Contents Links (Right) */
        .toc-title {
            font-size: 0.85rem;
            font-weight: 700;
            color: var(--accent-cyan);
            text-transform: uppercase;
            letter-spacing: 0.05em;
            border-bottom: 1px solid var(--border);
            padding-bottom: 10px;
        }
        .right-toc-list {
            list-style: none;
            display: flex;
            flex-direction: column;
            gap: 8px;
        }
        .right-toc-list li {
            padding: 0;
        }
        .right-toc-list li a {
            display: block;
            color: var(--text-secondary);
            text-decoration: none;
            font-size: 0.8rem;
            transition: color 0.2s, padding-left 0.2s;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            border-left: 2px solid transparent;
            padding-left: 8px;
        }
        .right-toc-list li a:hover, .right-toc-list li a.active {
            color: var(--accent-cyan);
            border-left-color: var(--accent-cyan);
        }
        .toc-group-title {
            font-size: 0.75rem;
            font-weight: 700;
            color: var(--text-primary);
            margin-top: 14px;
            margin-bottom: 4px;
            text-overflow: ellipsis;
            white-space: nowrap;
            overflow: hidden;
            border-bottom: 1px solid rgba(255, 255, 255, 0.05);
            padding-bottom: 2px;
        }
        
        .workspace {
            padding: 40px 4%;
            overflow-y: auto;
            position: relative;
        }
        .top-bar {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 40px;
            border-bottom: 1px solid var(--border);
            padding-bottom: 20px;
            flex-wrap: wrap;
            gap: 20px;
        }
        .overview-badge {
            display: inline-block;
            padding: 6px 16px;
            background-color: rgba(13, 148, 136, 0.1);
            color: var(--accent-teal);
            border: 1px solid rgba(13, 148, 136, 0.3);
            border-radius: 30px;
            font-size: 0.8rem;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            margin-bottom: 16px;
            font-family: var(--font-mono);
        }
        h1 {
            font-family: var(--font-title);
            font-size: 2.0rem;
            font-weight: 800;
            background: linear-gradient(135deg, #fff 0%, #a1a8b9 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            letter-spacing: -0.02em;
        }
        
        .search-container {
            display: flex;
            gap: 8px;
            background: rgba(255, 255, 255, 0.03);
            border: 1px solid var(--border);
            padding: 4px 8px;
            border-radius: 30px;
            width: 300px;
            transition: border-color 0.2s;
        }
        .search-container:focus-within {
            border-color: var(--accent-cyan);
        }
        .search-container input {
            background: none;
            border: none;
            color: #fff;
            padding: 6px 10px;
            font-size: 0.85rem;
            outline: none;
            flex: 1;
        }
        .search-container button {
            background: var(--accent-gradient);
            border: none;
            color: #0b0f19;
            font-weight: 700;
            padding: 6px 14px;
            border-radius: 20px;
            cursor: pointer;
            font-size: 0.8rem;
            transition: opacity 0.2s;
        }
        .search-container button:hover {
            opacity: 0.9;
        }
        
        .qa-list {
            display: flex;
            flex-direction: column;
            gap: 32px;
        }
        
        .summary-section {
            background-color: var(--bg-card);
            border: 1px solid var(--border);
            border-radius: 20px;
            padding: 35px;
            margin-bottom: 40px;
            transition: border-color 0.3s, box-shadow 0.3s, transform 0.2s;
            scroll-margin-top: 40px;
        }
        .summary-section:hover, .summary-section.search-focus {
            border-color: var(--accent-teal);
            box-shadow: 0 10px 40px rgba(13, 148, 136, 0.15);
        }
        .summary-section.search-focus {
            transform: scale(1.005);
        }
        
        .qa-card {
            background-color: var(--bg-card);
            border: 1px solid var(--border);
            border-radius: 16px;
            overflow: hidden;
            transition: transform 0.2s, border-color 0.3s, box-shadow 0.3s;
            scroll-margin-top: 40px;
        }
        .qa-card:hover, .qa-card.search-focus {
            border-color: var(--accent-cyan);
            box-shadow: 0 8px 30px rgba(6, 182, 212, 0.12);
        }
        .qa-card.search-focus {
            transform: scale(1.005);
        }
        
        .sec-header {
            margin-bottom: 24px;
            border-bottom: 1px solid var(--border);
            padding-bottom: 16px;
        }
        .sec-header h2 {
            font-family: var(--font-title);
            font-size: 1.4rem;
            font-weight: 700;
            color: #fff;
            letter-spacing: -0.01em;
        }
        .sec-body {
            color: var(--text-secondary);
            line-height: 1.8;
            font-size: 0.98rem;
            min-width: 0;
            overflow-wrap: break-word;
        }
        .sec-body strong {
            color: var(--text-primary);
            font-weight: 600;
        }
        .sec-body p {
            margin-bottom: 16px;
        }
        .sec-body p:last-child {
            margin-bottom: 0;
        }
        .sec-body h3 {
            font-family: var(--font-title);
            color: #fff;
            margin: 32px 0 14px 0;
            font-size: 1.2rem;
            border-bottom: 1px solid rgba(255,255,255,0.04);
            padding-bottom: 6px;
            scroll-margin-top: 60px;
        }
        .sec-body h4 {
            font-family: var(--font-title);
            color: var(--accent-cyan);
            margin: 24px 0 10px 0;
            font-size: 1.08rem;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 24px 0;
            font-size: 0.95rem;
            border-radius: 8px;
            overflow: hidden;
            border: 1px solid var(--border);
        }
        th, td {
            padding: 12px 16px;
            text-align: left;
        }
        th {
            background-color: rgba(255, 255, 255, 0.04);
            color: var(--text-primary);
            font-weight: 600;
            border-bottom: 1px solid var(--border);
        }
        td {
            color: var(--text-secondary);
            border-bottom: 1px solid var(--border);
            background-color: rgba(255, 255, 255, 0.01);
        }
        tr:last-child td {
            border-bottom: none;
        }
        tr:hover td {
            background-color: var(--bg-hover);
            color: var(--text-primary);
        }

        .qa-question {
            padding: 28px;
            background-color: rgba(255, 255, 255, 0.015);
            border-bottom: 1px solid var(--border);
            display: flex;
            gap: 18px;
            align-items: flex-start;
        }
        .q-badge {
            background: var(--accent-gradient);
            color: #0b0f19;
            font-family: var(--font-title);
            font-weight: 800;
            padding: 4px 12px;
            border-radius: 8px;
            font-size: 0.85rem;
            letter-spacing: 0.05em;
        }
        .q-content {
            font-weight: 600;
            font-size: 1.15rem;
            flex: 1;
            min-width: 0;
            line-height: 1.7;
            color: var(--text-primary);
            overflow-wrap: break-word;
        }
        .qa-answer {
            padding: 28px;
            display: flex;
            gap: 18px;
            align-items: flex-start;
        }
        .a-badge {
            background-color: rgba(255, 255, 255, 0.06);
            color: var(--text-primary);
            font-family: var(--font-title);
            font-weight: 800;
            padding: 4px 12px;
            border-radius: 8px;
            font-size: 0.85rem;
            border: 1px solid rgba(255, 255, 255, 0.05);
        }
        .a-content {
            flex: 1;
            min-width: 0;
            color: var(--text-secondary);
            line-height: 1.8;
            font-size: 0.98rem;
            overflow-wrap: break-word;
        }
        .a-content strong {
            color: var(--text-primary);
            font-weight: 600;
        }
        .a-content p { margin-bottom: 16px; }
        .a-content p:last-child { margin-bottom: 0; }
        .a-content h4 {
            font-family: var(--font-title);
            color: var(--accent-cyan);
            margin: 28px 0 12px 0;
            font-size: 1.2rem;
            border-bottom: 1px solid rgba(255,255,255,0.03);
            padding-bottom: 4px;
            scroll-margin-top: 60px;
        }
        
        pre {
            position: relative;
            background-color: #060913 !important;
            padding: 20px !important;
            border-radius: 10px;
            border: 1px solid var(--border);
            overflow-x: auto;
            margin: 20px 0;
        }
        code {
            font-family: var(--font-mono) !important;
            font-size: 0.9rem !important;
        }
        :not(pre) > code {
            background-color: rgba(236, 72, 153, 0.15);
            color: #f472b6;
            padding: 2px 6px;
            border-radius: 4px;
            font-weight: 600;
            border: 1px solid rgba(236, 72, 153, 0.2);
            word-break: break-word;
            cursor: pointer;
            transition: all 0.2s;
            display: inline-flex;
            align-items: center;
        }
        :not(pre) > code:hover {
            background-color: rgba(236, 72, 153, 0.3);
            border-color: rgba(236, 72, 153, 0.5);
        }
        :not(pre) > code::after {
            content: "📋";
            font-size: 0.8rem;
            margin-left: 6px;
            opacity: 0.5;
            transition: opacity 0.2s;
        }
        :not(pre) > code:hover::after {
            opacity: 1;
        }
        :not(pre) > code.copied::after {
            content: "✓";
            color: #4ade80;
            opacity: 1;
        }
        
        /* Reset inline code styling if it's inside a hyperlink */
        a code {
            background-color: transparent !important;
            color: inherit !important;
            padding: 0 !important;
            border: none !important;
            pointer-events: none; /* Let clicks pass through to the anchor tag */
            font-weight: inherit;
        }
        a code::after {
            display: none !important;
        }
        .copy-btn {
            position: absolute;
            top: 10px;
            right: 10px;
            background-color: rgba(255, 255, 255, 0.05);
            border: 1px solid rgba(255, 255, 255, 0.08);
            color: var(--text-secondary);
            font-size: 0.75rem;
            font-weight: 600;
            padding: 6px 12px;
            border-radius: 6px;
            cursor: pointer;
            transition: all 0.2s;
            opacity: 0;
            z-index: 10;
        }
        pre:hover .copy-btn {
            opacity: 1;
        }
        .copy-btn:hover {
            background-color: var(--accent-cyan);
            color: #0b0f19;
            border-color: var(--accent-cyan);
        }
        
        .alert {
            padding: 16px 20px;
            border-radius: 8px;
            margin: 20px 0;
            font-size: 0.92rem;
            line-height: 1.65;
        }
        .alert-note { background-color: rgba(6, 182, 212, 0.06); border-left: 4px solid var(--accent-cyan); color: #a5f3fc; }
        .alert-tip { background-color: rgba(13, 148, 136, 0.06); border-left: 4px solid var(--accent-teal); color: #99f6e4; }
        .alert-important { background-color: rgba(99, 102, 241, 0.06); border-left: 4px solid #6366f1; color: #c7d2fe; }
        .alert-warning { background-color: rgba(245, 158, 11, 0.06); border-left: 4px solid #f59e0b; color: #fef08a; }
        .alert-caution { background-color: rgba(239, 68, 68, 0.06); border-left: 4px solid #ef4444; color: #fca5a5; }
        .alert p { margin-bottom: 0; }
        
        .txt-highlight {
            background-color: rgba(250, 204, 21, 0.25);
            color: #facc15;
            border-radius: 4px;
            padding: 0 2px;
            box-shadow: 0 0 8px rgba(250, 204, 21, 0.3);
            font-weight: 600;
        }
        
        ul, ol { margin: 16px 0 16px 24px; }
        li { margin-bottom: 8px; line-height: 1.65; }
        
        a {
            color: var(--accent-cyan);
            text-decoration: none;
            transition: color 0.2s;
        }
        a:hover {
            color: #fff;
            text-decoration: none;
        }
        h2 a, h3 a, h4 a, h5 a {
            color: inherit !important;
            text-decoration: none !important;
        }
        
        footer {
            margin-top: 80px;
            text-align: center;
            color: var(--text-muted);
            font-size: 0.8rem;
            border-top: 1px solid var(--border);
            padding-top: 24px;
        }
        
        @media (max-width: 1100px) {
            body {
                grid-template-columns: 240px 1fr;
            }
            .right-sidebar {
                display: none;
            }
        }
        @media (max-width: 768px) {
            body {
                grid-template-columns: 1fr;
            }
            .left-sidebar, .right-sidebar {
                display: none;
            }
        }
    </style>
</head>
<body>
    <!-- Left Sidebar: Major Categorization -->
    <aside class="left-sidebar">
        <div class="brand">
            <div class="brand-logo"></div>
            <div class="brand-title">Q&A <span>{BRAND_SUB}</span></div>
        </div>
        <ul class="nav-list">
            {LEFT_TOC_ITEMS}
        </ul>
    </aside>
    
    <!-- Central Content Area -->
    <div class="workspace">
        <header class="top-bar">
            <div>
                <span class="overview-badge">{SUBTITLE}</span>
                <h1>{TITLE}</h1>
            </div>
            <div class="search-container">
                <input type="text" id="search-input" placeholder="세션 내 문자열 검색...">
                <button id="search-btn">검색</button>
            </div>
        </header>
        
        <div class="qa-list" id="content-container">
            {CONTENT}
        </div>
        
        <footer>
            Generated by Agent CLI qna-session Skill
        </footer>
    </div>
    
    <!-- Right Sidebar: Fine-grained Section TOC -->
    <aside class="right-sidebar">
        <div class="toc-title">세부 목차 (TOC)</div>
        <ul class="right-toc-list">
            {RIGHT_TOC_ITEMS}
        </ul>
    </aside>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/plugins/autoloader/prism-autoloader.min.js"></script>
    <script>
        function setupCopyButtons() {
            document.querySelectorAll('.copy-btn').forEach(btn => btn.remove());
            document.querySelectorAll('pre').forEach(pre => {
                const button = document.createElement('button');
                button.className = 'copy-btn';
                button.innerText = 'Copy';
                pre.appendChild(button);
                
                button.addEventListener('click', () => {
                    const code = pre.querySelector('code').innerText;
                    navigator.clipboard.writeText(code).then(() => {
                        button.innerText = 'Copied!';
                        setTimeout(() => { button.innerText = 'Copy'; }, 2000);
                    });
                });
            });
            
            // Inline code click-to-copy
            document.querySelectorAll(':not(pre) > code').forEach(inlineCode => {
                if (inlineCode.closest('a')) return; // Exclude code tags inside hyperlinks
                inlineCode.title = 'Click to copy';
                // Prevent duplicate listeners on re-runs
                inlineCode.replaceWith(inlineCode.cloneNode(true));
            });
            document.querySelectorAll(':not(pre) > code').forEach(inlineCode => {
                if (inlineCode.closest('a')) return; // Exclude code tags inside hyperlinks
                inlineCode.addEventListener('click', function() {
                    // Extract text but ignore the ::after pseudo-element content 
                    // which is handled purely by CSS, so innerText is safe
                    const textToCopy = this.innerText;
                    navigator.clipboard.writeText(textToCopy).then(() => {
                        const originalBg = this.style.backgroundColor;
                        this.classList.add('copied');
                        this.style.backgroundColor = 'rgba(74, 222, 128, 0.15)'; // Green flash
                        setTimeout(() => { 
                            this.classList.remove('copied');
                            this.style.backgroundColor = originalBg; 
                        }, 1200);
                    });
                });
            });
        }
        
        setupCopyButtons();
        
        // Make all external/content links open in a new tab
        document.querySelectorAll('a').forEach(link => {
            const href = link.getAttribute('href');
            if (href && !href.startsWith('#')) {
                link.setAttribute('target', '_blank');
                link.setAttribute('rel', 'noopener noreferrer');
            }
        });
        
        // Search functionality
        const searchInput = document.getElementById('search-input');
        const searchBtn = document.getElementById('search-btn');
        const contentContainer = document.getElementById('content-container');
        const originalContentHTML = contentContainer.innerHTML;
        
        function escapeRegExp(string) {
            return string.replace(/[.*+?^${}()|[\\\]\\\\]/g, '\\\\$&');
        }
        
        function highlightTextNodes(element, regex, onMatch) {
            const walk = document.createTreeWalker(element, NodeFilter.SHOW_TEXT, null, false);
            const nodesToReplace = [];
            
            let node;
            while (node = walk.nextNode()) {
                if (node.parentNode.nodeName === 'SCRIPT' || 
                    node.parentNode.nodeName === 'STYLE' || 
                    node.parentNode.nodeName === 'CODE' || 
                    node.parentNode.tagName === 'CODE' ||
                    node.parentNode.closest('pre')) {
                    continue;
                }
                if (regex.test(node.nodeValue)) {
                    nodesToReplace.push(node);
                }
            }
            
            nodesToReplace.forEach(node => {
                const parent = node.parentNode;
                if (!parent) return;
                
                const html = node.nodeValue.replace(regex, '<mark class="txt-highlight">$1</mark>');
                const temp = document.createElement('span');
                temp.innerHTML = html;
                
                while (temp.firstChild) {
                    parent.insertBefore(temp.firstChild, node);
                }
                parent.removeChild(node);
                onMatch(parent);
            });
        }
        
        function performSearch() {
            const query = searchInput.value.trim();
            contentContainer.innerHTML = originalContentHTML;
            setupCopyButtons();
            
            if (window.Prism) {
                Prism.highlightAllUnder(contentContainer);
            }
            
            const items = document.querySelectorAll('.qa-card, .summary-section');
            items.forEach(item => {
                item.classList.remove('search-focus');
                item.style.display = '';
            });
            
            if (query === '') return;
            
            const regex = new RegExp('(' + escapeRegExp(query) + ')', 'gi');
            let firstMatchedItem = null;
            
            const targetContainers = document.querySelectorAll('.q-content, .a-content, .sec-body, .sec-header h2');
            targetContainers.forEach(container => {
                highlightTextNodes(container, regex, (matchedNode) => {
                    if (!firstMatchedItem) {
                        firstMatchedItem = container.closest('.qa-card, .summary-section');
                    }
                });
            });
            
            if (firstMatchedItem) {
                firstMatchedItem.classList.add('search-focus');
                firstMatchedItem.scrollIntoView({ behavior: 'smooth', block: 'center' });
            }
        }
        
        searchBtn.addEventListener('click', performSearch);
        searchInput.addEventListener('input', performSearch);
        searchInput.addEventListener('keyup', (e) => {
            if (e.key === 'Enter') performSearch();
        });
        
        // TOC ScrollSpy (Highlights right TOC as you scroll or click)
        const spySections = document.querySelectorAll('.summary-section [id*="-b"], .qa-card');
        const rightTocLinks = document.querySelectorAll('.right-toc-list li a');
        
        function highlightRightTocOnScroll() {
            let fromTop = window.scrollY + 120;
            let activeSet = false;
            
            // Loop backwards to find the current active section
            for (let i = spySections.length - 1; i >= 0; i--) {
                const section = spySections[i];
                if (section.offsetTop <= fromTop) {
                    const id = section.getAttribute('id');
                    if (id) {
                        rightTocLinks.forEach(link => {
                            if (link.getAttribute('href') === '#' + id) {
                                link.classList.add('active');
                            } else {
                                link.classList.remove('active');
                            }
                        });
                        activeSet = true;
                        break;
                    }
                }
            }
            if (!activeSet && rightTocLinks.length > 0) {
                rightTocLinks.forEach(l => l.classList.remove('active'));
            }
        }
        
        window.addEventListener('scroll', highlightRightTocOnScroll);
        
        // Link click navigation with custom styling toggles
        document.querySelectorAll('.nav-list li a').forEach(a => {
            a.addEventListener('click', () => {
                document.querySelectorAll('.nav-list li a').forEach(el => el.classList.remove('active'));
                a.classList.add('active');
            });
        });
        
        document.querySelectorAll('.right-toc-list li a').forEach(a => {
            a.addEventListener('click', () => {
                document.querySelectorAll('.right-toc-list li a').forEach(el => el.classList.remove('active'));
                a.classList.add('active');
            });
        });
    </script>
</body>
</html>
"""
    rendered = template.replace("{TITLE}", title)
    rendered = rendered.replace("{SUBTITLE}", subtitle)
    rendered = rendered.replace("{BRAND_SUB}", brand_sub)
    rendered = rendered.replace("{LEFT_TOC_ITEMS}", left_toc)
    rendered = rendered.replace("{RIGHT_TOC_ITEMS}", right_toc)
    rendered = rendered.replace("{CONTENT}", content_cards)
    return rendered

def build_qna_html(num, qa_list):
    html_file = os.path.join(WORKING_DIR, "qna{}.html".format(num))
    
    left_toc = ""
    right_toc = ""
    qa_cards = ""
    
    for qa in qa_list:
        clean_q = qa['question_md'].split('\n')[0].strip()
        clean_q = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", clean_q)
        if len(clean_q) > 22:
            clean_q = clean_q[:22] + "..."
            
        card_id = "qa-q{}".format(qa["num"])
        left_toc += '<li><a href="#{}"><span class="num-badge">Q{}</span> {}</a></li>\n'.format(card_id, qa["num"], clean_q)
        
        right_toc += '<li><a href="#{}">Q{} Detail View</a></li>\n'.format(card_id, qa["num"])
        
        qa_cards += """
        <div class="qa-card" id="{}">
            <div class="qa-question">
                <span class="q-badge">Q{}</span>
                <div class="q-content">{}</div>
            </div>
            <div class="qa-answer">
                <span class="a-badge">A</span>
                <div class="a-content">{}</div>
            </div>
        </div>
        """.format(card_id, qa['num'], qa['question_html'], qa['answer_html'])
        
    title = "Q&A 세션 {} 상세 내역".format(num)
    rendered = generate_html_string(title, left_toc, qa_cards, right_toc, is_overall=False)
    
    with open(html_file, "w", encoding="utf-8") as f:
        f.write(rendered)
    print("HTML_CREATED:{}".format(html_file))

def build_overall_html(num, qa_list):
    overall_file = os.path.join(WORKING_DIR, "qna{}-overall.html".format(num))
    
    topic_data = compile_overall_by_topics(qa_list)
    
    left_toc = ""
    right_toc = ""
    summary_cards = ""
    
    topic_ids = {
        "framework": "topic-framework",
        "features": "topic-features",
        "monetization": "topic-monetization",
        "environment": "topic-environment",
        "uncategorized": "topic-uncategorized"
    }
    
    for key, info in topic_data.items():
        if not info["blocks"]:
            continue
            
        topic_id = topic_ids[key]
        clean_title = info["title"]
        
        left_toc += '<li><a href="#{}">{}</a></li>\n'.format(topic_id, clean_title)
        right_toc += '<li class="toc-group-title">{}</li>\n'.format(clean_title)
        
        block_htmls = []
        for b_idx, b in enumerate(info["blocks"]):
            block_id = "{}-b{}".format(topic_id, b_idx)
            
            # Format indentation padding-left according to raw heading depth (3, 4, 5)
            # depth 3 -> 8px, depth 4 -> 20px, depth 5 -> 32px
            pad_left = (b["depth"] - 3) * 12 + 8
            
            short_h = b["header"]
            if len(short_h) > 22:
                short_h = short_h[:22] + "..."
            right_toc += '<li><a href="#{}" style="padding-left: {}px;">{}</a></li>\n'.format(block_id, pad_left, short_h)
            
            block_htmls.append("""
            <div style="margin-bottom: 32px;" id="{}">
                <h3 style="margin-top: 16px;">{}</h3>
                <div style="margin-top: 10px;">{}</div>
            </div>
            """.format(block_id, b["header"], b["content_html"]))
            
        summary_cards += """
        <div class="summary-section" id="{}">
            <div class="sec-header">
                <h2>{}</h2>
            </div>
            <div class="sec-body">
                {}
            </div>
        </div>
        """.format(topic_id, clean_title, "\n".join(block_htmls))
        
    title = "Q&A 세션 {} 종합 요구사항 기술 사양서".format(num)
    rendered = generate_html_string(title, left_toc, summary_cards, right_toc, is_overall=True)
    
    with open(overall_file, "w", encoding="utf-8") as f:
        f.write(rendered)
    print("OVERALL_CREATED:{}".format(overall_file))

def generate_overall_markdown(qa_list, session_num):
    topic_data = compile_overall_by_topics(qa_list)
    
    overall_md = "# Q&A 세션 {} 종합 요구사항 기술 사양 보고서\n\n".format(session_num)
    overall_md += "이 문서는 세션 진행 중 수집된 요구사항 질문 답변 리스트를 핵심 주제별로 분류하여 종합 구성한 기술 보고서입니다.\n\n"
    
    overall_md += "## 📋 종합 목차 (TOC)\n\n"
    for key, info in topic_data.items():
        if info["blocks"]:
            anchor = key
            overall_md += "* [{}](#{})\n".format(info["title"], anchor)
    overall_md += "\n---\n\n"
    
    for key, info in topic_data.items():
        if not info["blocks"]:
            continue
        overall_md += "## <a name=\"{}\"></a>{}\n\n".format(key, info["title"])
        for b in info["blocks"]:
            overall_md += "### {}\n\n".format(b["header"])
            overall_md += "{}\n\n".format(b["content_md"])
        overall_md += "---\n\n"
        
    overall_md += "📢 *Generated by Agent CLI Export Manager*"
    return overall_md

def finalize_session(num):
    md_file = os.path.join(WORKING_DIR, "qna{}.md".format(num))
    if not os.path.exists(md_file):
        print("ERROR: md file not found: {}".format(md_file))
        sys.exit(1)
        
    qa_list = parse_md_to_qa_list(md_file)
    if not qa_list:
        print("ERROR: no QA pairs parsed")
        sys.exit(1)
        
    build_qna_html(num, qa_list)
    build_overall_html(num, qa_list)
    print("FINALIZE_COMPLETE")

def do_export(session_file, session_num, format_arg, type_arg, output_arg):
    md_path = None
    if session_file:
        if os.path.isabs(session_file):
            md_path = session_file
        else:
            md_path = os.path.join(WORKSPACE_ROOT, session_file)
    else:
        if not session_num:
            ensure_working_dir()
            session_num = 1
            while True:
                next_path = os.path.join(WORKING_DIR, "qna{}.md".format(session_num + 1))
                if os.path.exists(next_path):
                    session_num += 1
                else:
                    break
        md_path = os.path.join(WORKING_DIR, "qna{}.md".format(session_num))

    if not os.path.exists(md_path):
        print("ERROR: Source session markdown not found: {}".format(md_path))
        sys.exit(1)

    base = os.path.splitext(os.path.basename(md_path))[0]
    qa_list = parse_md_to_qa_list(md_path)

    if format_arg == "html":
        default_name = "{}-overall.html".format(base) if type_arg == "overall" else "{}.html".format(base)
    else:
        default_name = "{}-overall.md".format(base) if type_arg == "overall" else "{}-raw.md".format(base)
        
    dest_path = resolve_output_path(output_arg, default_name)

    if format_arg == "html":
        if type_arg == "overall":
            topic_data = compile_overall_by_topics(qa_list)
            left_toc = ""
            right_toc = ""
            content_cards = ""
            
            topic_ids = {
                "framework": "topic-framework",
                "features": "topic-features",
                "monetization": "topic-monetization",
                "environment": "topic-environment",
                "uncategorized": "topic-uncategorized"
            }
            
            for key, info in topic_data.items():
                if not info["blocks"]:
                    continue
                topic_id = topic_ids[key]
                left_toc += '<li><a href="#{}">{}</a></li>\n'.format(topic_id, info["title"])
                right_toc += '<li class="toc-group-title">{}</li>\n'.format(info["title"])
                
                block_htmls = []
                for b_idx, b in enumerate(info["blocks"]):
                    block_id = "{}-b{}".format(topic_id, b_idx)
                    pad_left = (b["depth"] - 3) * 12 + 8
                    
                    short_h = b["header"]
                    if len(short_h) > 22:
                        short_h = short_h[:22] + "..."
                    right_toc += '<li><a href="#{}" style="padding-left: {}px;">{}</a></li>\n'.format(block_id, pad_left, short_h)
                    
                    block_htmls.append("""
                    <div style="margin-bottom: 32px;" id="{}">
                        <h3 style="margin-top: 16px;">{}</h3>
                        <div style="margin-top: 10px;">{}</div>
                    </div>
                    """.format(block_id, b["header"], b["content_html"]))
                    
                content_cards += """
                <div class="summary-section" id="{}">
                    <div class="sec-header">
                        <h2>{}</h2>
                    </div>
                    <div class="sec-body">
                        {}
                    </div>
                </div>
                """.format(topic_id, info["title"], "\n".join(block_htmls))
        else:
            left_toc = ""
            right_toc = ""
            content_cards = ""
            for qa in qa_list:
                clean_q = qa['question_md'].split('\n')[0].strip()
                clean_q = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", clean_q)
                if len(clean_q) > 22:
                    clean_q = clean_q[:22] + "..."
                card_id = "qa-q{}".format(qa["num"])
                left_toc += '<li><a href="#{}"><span class="num-badge">Q{}</span> {}</a></li>\n'.format(card_id, qa["num"], clean_q)
                right_toc += '<li><a href="#{}">Q{} Details</a></li>\n'.format(card_id, qa["num"])
                content_cards += """
                <div class="qa-card" id="{}">
                    <div class="qa-question">
                        <span class="q-badge">Q{}</span>
                        <div class="q-content">{}</div>
                    </div>
                    <div class="qa-answer">
                        <span class="a-badge">A</span>
                        <div class="a-content">{}</div>
                    </div>
                </div>
                """.format(card_id, qa['num'], qa['question_html'], qa['answer_html'])
                
        title = "{} 종합 요구사항 기술 사양서".format(base) if type_arg == "overall" else "{} 상세 기록".format(base)
        html_out = generate_html_string(title, left_toc, content_cards, right_toc, is_overall=(type_arg == "overall"))
        
        with open(dest_path, "w", encoding="utf-8") as f:
            f.write(html_out)
        print("EXPORT_SUCCESS:{}".format(dest_path))
        
    elif format_arg == "md" or format_arg == "raw":
        if type_arg == "overall" and format_arg == "md":
            md_out = generate_overall_markdown(qa_list, session_num or "Exported")
            with open(dest_path, "w", encoding="utf-8") as f:
                f.write(md_out)
        else:
            shutil.copy2(md_path, dest_path)
            
        print("EXPORT_SUCCESS:{}".format(dest_path))

def main():
    parser = argparse.ArgumentParser(description="Agent Q&A Session Manager")
    parser.add_argument("action", choices=["init", "append", "finalize", "export"])
    parser.add_argument("--num", type=int, help="Session number")
    parser.add_argument("--q", type=str, help="Question text")
    parser.add_argument("--a", type=str, help="Answer text")
    parser.add_argument("--session_file", type=str, help="Custom path to raw Q&A session markdown file")
    parser.add_argument("--format", choices=["html", "md", "raw"], help="Target format for export")
    parser.add_argument("--type", choices=["overall", "raw"], default="raw", help="Target output style")
    parser.add_argument("--output", type=str, help="Optional destination path for the exported file")
    
    args = parser.parse_args()
    
    if args.action == "init":
        init_session()
    elif args.action == "append":
        if not args.num or not args.q or not args.a:
            print("ERROR: --num, --q, --a are required for append")
            sys.exit(1)
        append_qna(args.num, args.q, args.a)
    elif args.action == "finalize":
        if not args.num:
            print("ERROR: --num is required for finalize")
            sys.exit(1)
        finalize_session(args.num)
    elif args.action == "export":
        if not args.format:
            print("ERROR: --format is required for export action")
            sys.exit(1)
        do_export(args.session_file, args.num, args.format, args.type, args.output)

if __name__ == "__main__":
    main()
